[package]
name = "rust-httpv1-server"
version = "0.1.0"
authors = ["josephframpton <josephjamesframpton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
